version: '3.9'

services:
  api:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database
    restart: always
    environment:
      - PORT=8080
      - DBUSER=postgres
      - DBPASSWORD=password
      - DBHOST=database
      - DBPORT=5432
      - DBNAME=crypto-wallets

  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=crypto-wallets
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 20s
      retries: 5