version: '3.9'

services:
  api:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database
    restart: always
    environment:
      - SERVER_PORT=8080
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=crypto-wallets
      - TICKERS_INTERVAL_SECONDS=300
      - TICKERS_URL=https://api.coincap.io/v2/assets
      - TOKEN_EXPIRATION=24
      - TOKEN_SECRET_KEY=

  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=crypto-wallets
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 20s
      retries: 5